import { Product } from './types/Product';

export const sampleProducts: Product[] = [
    {
        name: 'Chocolate Cake Pop',
        slug: 'chocolate-cake-pop',
        image: '../images/p1.jpg',
        category: 'Cakepop',
        cook: 'Bobby',
        price: 2,
        countInStock: 24,
        description: 'Chocolate cake pop in an ice cream cone filled with chocolate candy.',
        rating: 4.5,
        numReviews: 6,
    },
    {
        name: 'Strawberry Cake Pop',
        slug: 'strawberry-cake-pop',
        image: '../images/p2.jpg',
        category: 'Cakepop',
        cook: 'Bobby',
        price: 2,
        countInStock: 24,
        description: 'Strawberry cake pop in an ice cream cone filled with chocolate candy.',
        rating: 4.5,
        numReviews: 6,
    },
    {
        name: 'Vanilla Cake Pop',
        slug: 'vanilla-cake-pop',
        image: '../images/p3.jpg',
        category: 'Cakepop',
        cook: 'Bobby',
        price: 2,
        countInStock: 24,
        description: 'Vanilla cake pop in an ice cream cone filled with chocolate candy.',
        rating: 4.5,
        numReviews: 6,
    },
];
